keys:
  - &revol-xut 91EBE87016391323642A6803B966009D57E69CC6
  - &bothe age1vw8k7hsj26rmm3aehcxpnue0m43stwlwhxdk5tzvw3zvuvxxcyaq233555
creation_rules:
  - path_regex: secrets/bothe\.yaml$
    key_groups:
    - pgp:
      - *revol-xut
      age:
      - *bothe

