icons_format = "{icon}"

[theme]
theme = "dracula"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
format = "$icon $barchart $utilization"

[[block]]
block = "temperature"

[[block]]
block = "battery"

[[block]]
block = "maildir"
interval = 1
inboxes = [ "/home/revol-xut/Maildir/tu-dresden/Inbox", "/home/revol-xut/Maildir/ifsr/Inbox" ]
threshold_warning = 1
threshold_critical = 10
display_type = "new"
[[block.click]]
button = "left"
cmd = "alacritty -e /home/revol-xut/.config/sway/lauch_neomutt"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "bluetooth"

disconnected_format = ""
#hide_disconnected = false
# hide_disconnected = true
mac = "88:D0:39:6D:AD:14"
format = "BT {percentage}"
#format_unavailable = "_"

[[block]]
timezone = "Europe/Berlin"
format = " $timestamp.datetime(f:'%H:%M %Z') "
block = "time"
interval = 5

[[block]]
timezone = "America/Los_Angeles"
block = "time"
interval = 5
